require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end


task :test do
    puts "Executando uma tarefa de teste"
end

task :local_seeds do
    CONFIG = YAML.load_file(File.join(Dir.pwd, "feactures/suport/config/local.yml"))

    users = [
      { name: "Yago UZ", email: "yago@equipo.com.br", password: to_md5("pwd123") },
      { name: "Laylla Rodrigues", email: "laylla.rodrigues@hotmail.com", password: to_md5("pwd123") },
      { name: "Laylla Rodrigues", email: "laylla1@hotmail.com", password: to_md5("pwd123") },
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)
end

task :hmg_seeds do
    CONFIG = YAML.load_file(File.join(Dir.pwd, "feactures/suport/config/hmg.yml"))

    users = [
      { name: "Yago UZ", email: "yago@equipo.com.br", password: to_md5("pwd123") },
      { name: "Laylla Rodrigues", email: "laylla.rodrigues@hotmail.com", password: to_md5("pwd123") },
      { name: "Laylla Rodrigues", email: "laylla1@hotmail.com", password: to_md5("pwd123") },
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)
end